version: '2'
services:
  mysql_db:
   image: mysql:latest
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
  
  